site_name: Marketing Data Foundation
nav:
  - index.md

site_url: ""
use_directory_urls: false
plugins:
  - macros
  - dataopslive
  - search
  - offline
theme:
  name: material
  features:
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.annotation
    - navigation.footer
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: light-blue
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: light-blue
      accent: light-blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - md_in_html
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.blocks.html

extra:
  account_locator: !ENV [DATAOPS_SOLE_ACCOUNT, '<account_locator>']
  analytics:
    provider: google
    property: G-NF9VCFV30G
  generator: false
