DROP DATABASE IF EXISTS LLM_DEMO;
DROP DATABASE IF EXISTS C360_SAMPLE_DB;
DROP DATABASE IF EXISTS DATA_QUALITY_NOTEBOOKS;
DROP DATABASE IF EXISTS FIVETRAN_CONNECTOR_DEMO;
DROP DATABASE IF EXISTS OMNATA_CONNECTOR_DEMO;
DROP DATABASE IF EXISTS MARKETING_DATA_FOUNDATION_V3;
DROP DATABASE IF EXISTS MARKETING_DATA_FOUNDATION_STARTER_V3_<USERNAME>;
DROP DATABASE IF EXISTS MARKETING_DATA_FOUNDATION_STARTER_V3_PKG_<USERNAME>;

DROP WAREHOUSE IF EXISTS MARKETING_DATA_FOUNDATION_WAREHOUSE;

DROP COMPUTE POOL IF EXISTS MARKETING_DATA_FOUNDATION_COMPUTE_POOL;