from services.application import Application

# DATABASE
APPLICATION = Application().database
CONFIGURATION_SCHEMA = "CONFIGURATION"
UNIFIED_MODEL_SCHEMA = "CAMPAIGN_INTELLIGENCE_COMBINED"

CAMPAIGN_PERFORMANCE = "CAMPAIGN_PERFORMANCE"
INFORMATION_SCHEMA = "INFORMATION_SCHEMA"
APPLICATION_KEY = "APPLICATION"

# COLUMNS
MODEL_ID_COL = "MODEL_ID"
SOURCE_ID_COL = "SOURCE_ID"
MODEL_UI_COL = "MODEL_UI"
PROCESS_ID_COL = "PROCESS_ID"
PROCESS_NAME_COL = "PROCESS_NAME"
MODEL_NAME_COL = "MODEL_NAME"
DATE_COLUMN = "DATE"
MONTH_COLUMN = "MONTH"
YEAR_COLUMN = "YEAR"
MONTH_YEAR_COLUMN = "MONTH-YEAR"
CLICKS_COLUMN = "CLICKS"
SPEND_COLUMN = "SPEND"
SORT_DATE_COLUMN = "SORT_DATE"
SPEND_PER_CLICKS_COLUMN = "SPEND_PER_CLICKS"
FACEBOOK_ADS_COL = "FACEBOOK"
LINKEDIN_ADS_COL = "LINKEDIN"
YEAR_DATA_COL = "YEAR_DATA"
OVERALL_SPEND_COL = "OVERALL_SPEND"
PLATFORM_NAME_COL = "PLATFORM_NAME"
ACCOUNT_NAME_COL = "ACCOUNT_NAME"
CAMPAIGN_NAME_COL = "CAMPAIGN_NAME"
AD_GROUP_NAME_COL = "AD_GROUP_NAME"
IMPRESSIONS_COL = "IMPRESSIONS"
PLATFORM_TOTAL_IMPRESSIONS_COL = "PLATFORM_TOTAL_IMPRESSIONS"
PLATFORM_TOTAL_SPEND_COL = "PLATFORM_TOTAL_SPEND"
VALUE_COL = "value"
SPEND_PER_CLICK = "SPEND PER CLICK"
REACTIONS = "REACTIONS"
TEMPLATE_COL = "TEMPLATE"
TABLE_CATALOG_COL = "TABLE_CATALOG"
TABLES_COL = "TABLES"
TABLE_NAME_COL = "TABLE_NAME"

PROCESS_ATTRIBUTES_COL = "PROCESS_ATTRIBUTES"
DEFINITIONS_COL = "definitions"
SOURCE_COL = "source"
OBJECT_COL = "object"
TARGETS_COL = "targets"

## INFO SCHEMA
TABLE_CATALOG_COL = "TABLE_CATALOG"
TABLE_SCHEMA_COL = "TABLE_SCHEMA"
TABLE_NAME_COL = "TABLE_NAME"
COLUMN_NAME_COL = "COLUMN_NAME"
COLUMNS_COL = "COLUMNS"
DATA_TYPE_COL = "DATA_TYPE"

# KEYS
DRAFT_KEY = "DRAFT"
ID_KEY = "ID"
IDS_KEY = "IDS"
PROCESS_ID_KEY = "PROCESS_ID"
STATUS_COL = "STATUS"
NAME_KEY = "NAME"
QUOTED_NAME_KEY = '"name"'
LOWER_NAME_KEY = "name"
CONNECTOR_ID_KEY = "CONNECTOR_ID"
CONNECTOR_NAME_COL = "CONNECTOR_NAME"
SOURCE_ID_COL = "SOURCE_ID"
SOURCES_KEY = "SOURCES"
PROVIDER_ID_COL = "PROVIDER_ID"
PROVIDER_NAME_COL = "PROVIDER_NAME"
DATABASE_COL = "DATABASE"
SCHEMA_COL = "SCHEMA"
CREATED_TIMESTAMP_COL = "CREATED_TIMESTAMP"
MODIFIED_TIMESTAMP_COL = "MODIFIED_TIMESTAMP"
DATABASE_NAME_KEY = "DATABASE_NAME"
SCHEMA_NAME_KEY = "SCHEMA_NAME"
PROCESS_NAME_KEY = "process_name"
PROCESS_TYPE_ID_KEY = "process_type_id"
SOURCE_DATABASE = "sourceDatabase"
SOURCE_SCHEMA = "sourceSchema"

TARGET_KEY = "target"
OBJECT_KEY = "object"


# TABLES
SOURCES_TABLE = "SOURCES"
CONNECTORS_TABLE = "CONNECTORS"
PROVIDERS_TABLE = "PROVIDERS"
PROCESS_TYPES_TABLE = "PROCESS_TYPES"
PROCESSES_TABLE = "PROCESSES"
MODELS_TABLE = "MODELS"

# SCHEMAS
METADATA_SCHEMA = "METADATA"

# RESPONSES
DELETED_SOURCES_KEY = "DELETED_SOURCES"

# CHATBOT
# SCHEMAS
LLM_SCHEMA = "LLM"
LLM_SEMANTIC_MODEL_STAGE = "SEMANTIC_MODEL"
LLM_CONFIGURATION_STAGE = "CONFIGURATION"
LLM_CONFIGURATION_FILE = "assistant_config.yaml"

API = "mobilize.snowflakecomputing.com"
TAG = '\'{"origin":"sf_sit","name":"Marketing Data Foundation","version":{"major":0, "minor":1},"attributes":""}\''

# TABLES
ASSISTANT_TABLE = "ASSISTANT"
ASSISTANT_TABLE_ID_COL = "ID"
ASSISTANT_TABLE_NAME_COL = "NAME"
ASSISTANT_TABLE_TYPE_COL = "ASSISTANT"
ASSISTANT_TABLE_SYS_PROMPT_COL = "SYS_PROMPT"
ASSISTANT_TABLE_CHAT_COL = "CHAT"
ASSISTANT_TABLE_USER_COL = "USER"
C360_TABLE = "C360_CLICKS_CRM_JOINED_VW"

